# Generated by Django 3.2.7 on 2022-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0015_rename_product_state_order_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
