# Generated by Django 3.2.7 on 2022-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce', '0016_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Sale', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='copon',
            field=models.ManyToManyField(blank=True, null=True, to='ecommarce.Copons'),
        ),
    ]
